server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_plazoleta
    username: root
    password: root

  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
  application:
    name: ms-plazoleta
appDescription: "Pragma Powerup"
appVersion: "1.0.0"